---
- hosts: localhost
  become: yes

  tasks:
    - name: Install apt dependencies
      apt:
        name:
          - golang
        state: latest

    - name: Add dwc2 to device tree overlay boot config
      lineinfile:
        path: /boot/config.txt
        line: "dtoverlay=dwc2"
        state: present

    - name: Dynamically load dwc2 to device tree overlay
      command: dtoverlay dwc2

    - name: Copy modules config
      copy:
        src: usb-gadget.conf
        dest: /etc/modules-load.d/usb-gadget.conf
        mode: 0644

    - name: Make pimk config directory
      file:
        path: /etc/pimk
        state: directory
        mode: 0755

    - name: Copy default pimk config
      copy:
        src: default.conf
        dest: /etc/pimk

    - name: Build pimk
      command: go build pimk.go

    - name: Copy pimk to path
      copy:
        src: pimk
        dest: /usr/local/bin/pimk
        mode: 0755

    - name: Copy pimk systemd service file
      copy:
        src: pimk.service
        dest: /etc/systemd/system/pimk.service
        mode: 0755

    - name: Enable pimk service
      systemd:
        daemon_reload: yes
        name: pimk.service
        state: restarted
        enabled: yes
